### ISSUE TITLE
Error connection 

### ISSUE THREAD

**Issue by arsa24** [Mengkodingan/ckptw#26]
Is this an error because of the code I wrote or is it my connection that is the problem?

`const {Client, Events} = require("@mengkodingan/ckptw")

const bot = new Client({
	printQRInTerminal: true,
	prefix: ".",
	readIncommingMsg: true
})

bot.ev.once(Events.ClientReady, (m) => {
    console.log(`ready at ${m.user.id}`);
});

bot.launch()`

connection closed due to  Error: Connection Failure
    at WebSocketClient.<anonymous> (/data/data/com.termux/files/home/botwa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:529:13)
    at WebSocketClient.emit (node:events:519:28)
    at /data/data/com.termux/files/home/botwa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:241:35
    at Object.decodeFrame (/data/data/com.termux/files/home/botwa/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:149:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  data: { reason: '405', location: 'rva' },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: {
      statusCode: 405,
      error: 'Method Not Allowed',
      message: 'Connection Failure'
    },
    headers: {}
  }
} , reconnecting  true

**Comment by CauaCodeDev** [comment]
Add inside the call: new Cliente: 
WAVersion: [2, 3000, 1015901307]

Example:
const client = new Client({
    WAVersion: [2, 3000, 1015901307], 
});
